name: Rust

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master ]

env:
  RUST_BACKTRACE: full
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Clippy
      run: cargo clippy -- -Dwarnings
    - name: Run tests
      run: cargo test --verbose
